[package]
name = "arrive"
version = "0.1.0"
authors = ["Marcin Puc <tranzystorek.io@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "arv"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
clap_complete = "4.0"
dirs = "4.0"
minreq = { version = "2.6", features = ["https"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
